#!/bin/bash
ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
echo "Currently in $ROOT";
set -x;

[ -e "$ROOT/activate" ] && rm $ROOT/activate;
for f in $ROOT/{build,dist,include,lib,venv}; do
    [ -d "$f" ] && rm -r "$f"
done;

set +x;
