* GLEAM

\textbf{G}ravitational \textbf{LE}ns \textbf{A}nalysis \textbf{M}odule

** Binaries

GLEAM is avaiable as a standalone app for macOS.
Simply download the lates release and double-click to run...
To use the full framework however, clone the repository and add it to your ~PYTHONPATH~ (e.g. in your ~.bashrc~ file).

** Install

To install GLEAM manually, simply open the terminal and run

#+BEGIN_SRC bash
./configure
./install
#+END_SRC
  
This will unpack, compile, and install all the necessary dependencies.
    
** Content

*** gleam/skycoords.py
Framework for reading astronomical coordinates such as /J2000/, /RA/Dec/, etc.
Is able to convert between different coordinate systems, and interfaces particularly well with
the MegaPipe pixel coordinate system.

*** gleam/skyf.py
Reads in a single ~.fits~ file and extracts general information on the observation.
Also contains several plotting procedures which visualize the data.

*** gleam/skypatch.py
Reads in a set of ~.fits~ files and extracts general information on the observation in different bands,
analogously to ~skyf.py~ (importing ~skyf.py~). Visualizes data as stacked or palette image.

*** gleam/lensobject.py
Inherits from ~SkyF~. Additionally extracts properties important for gravitational lenses
and lensed sources.
Visualizes these properties on top of inherited plotting procedures.

*** gleam/multilens.py
Inherits from ~SkyPatch~. Additionally extracts properties important for gravitational lenses
and lensed sources, analogously to ~lensobject.py~.
Visualizes these properties on top of inherited plotting procedures as stacked or palette image.
- TODO: Figure out a way to unify all lens properties!

*** gleam/lensfinder.py
A simple peak finder to extract lens and source image positions.
Uses very crude procedures, whose parameters have to be fine-tuned.
Provides an automatic lens detection feature to the LensObject class.
- TODO: Write a main method for use as a script!

*** gleam/glscfactory.py
GLASS config-file generator.
Features a sync and config reading feature with LensObject class.
Can be used to write config files for LensObject class instances, or to extract config files from LensObject class instances.
- TODO: Write a main method for use as a script!

*** gleam/app.py
- TODO: all, including TEST
    
** More
  + standardize docstrings and use sphinx to auto-generate Documentation page
  + update closest_node in cutsky.py to comply with python 3
