#!/bin/bash
#
# @author: phdenzel
#

ROOT="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
GLEAM_ROOT="$ROOT/gleam"

TESTCASES=("skycoords.py" "skyf.py" "skypatch.py" "lensobject.py" "multilens.py" \
                          "glscfactory.py" "lensfinder.py" \
                          "gui.py" \
                          "model/sersic.py" "model/spep.py" "model/spemd.py")

# Python 2 tests
PYTHON="python"
for c in ${TESTCASES[*]}; do
    $PYTHON $GLEAM_ROOT/$c -t
done;

# Python 3 tests
PYTHON="python3"
for c in ${TESTCASES[*]}; do
    $PYTHON $GLEAM_ROOT/$c -t
done;
